### ISSUE TITLE
Syntax error in serial build

### ISSUE THREAD

**Issue by SeanBryan51** [CABLE-LSM/CABLE#153]
The build script fails when building the serial executable and produces the following error:
```
ifort -O2 -fp-model precise  -I/apps/netcdf/4.6.3/include/Intel -c cbl_latent_heat.F90
cbl_latent_heat.F90(21): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: ( : % [ . = =>
  vkfeopge
----------^
cbl_latent_heat.F90(21): error #6218: This statement is positioned incorrectly and/or has syntax errors.
  vkfeopge
--^
compilation aborted for cbl_latent_heat.F90 (code 1)
make: *** [Makefile:167: cbl_latent_heat.o] Error 1
```

To reproduce:
```
git checkout main
git reset --hard 1c18b0d08f1fe6a8141466493a21eb1c77e9adb2
cd src/offline/
./build3.sh
```

**Comment by JhanSrbinovsky** [comment]
Looks like your problem is in latent heat, not the build script. Grepping in the trunk version of latent heat there is no occurrence 0f “pge”. I sugget you compare against that. Hope this helps. Jhan

From: Sean Bryan ***@***.***>
Date: Friday, 17 November 2023 at 10:02 am
To: CABLE-LSM/CABLE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CABLE-LSM/CABLE] Syntax error in serial build (Issue #153)

The build script fails when building the serial executable and produces the following error:

ifort -O2 -fp-model precise  -I/apps/netcdf/4.6.3/include/Intel -c cbl_latent_heat.F90

cbl_latent_heat.F90(21): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: ( : % [ . = =>

  vkfeopge

----------^

cbl_latent_heat.F90(21): error #6218: This statement is positioned incorrectly and/or has syntax errors.

  vkfeopge

--^

compilation aborted for cbl_latent_heat.F90 (code 1)

make: *** [Makefile:167: cbl_latent_heat.o] Error 1

To reproduce:

git checkout main

git reset --hard 1c18b0d08f1fe6a8141466493a21eb1c77e9adb2

cd src/offline/

./build3.sh

**Comment by SeanBryan51** [comment]
Yep this line looks like the culprit:

https://github.com/CABLE-LSM/CABLE/blob/1c18b0d08f1fe6a8141466493a21eb1c77e9adb2/src/science/canopy/cbl_latent_heat.F90#L21

Removing this line should fix the issue. Making a PR now.

**Comment by JhanSrbinovsky** [comment]
Where did that ever come from? It definitely isn’t in the trunk version? So does this mean you have migrated the ***@***.***,au. To github? I don’t want to be a worry wart – but do you have any idea where would something like this creep in?

From: Sean Bryan ***@***.***>
Date: Friday, 17 November 2023 at 10:20 am
To: CABLE-LSM/CABLE ***@***.***>
Cc: Srbinovsky, Jhan (Environment, Aspendale) ***@***.***>, Comment ***@***.***>
Subject: Re: [CABLE-LSM/CABLE] Syntax error in serial build (Issue #153)

Yep this line looks like the culprit:

https://github.com/CABLE-LSM/CABLE/blob/1c18b0d08f1fe6a8141466493a21eb1c77e9adb2/src/science/canopy/cbl_latent_heat.F90#L21

Removing this line should fix the issue. Making a PR now.

**Comment by SeanBryan51** [comment]
The `git blame` command shows which commits had modified a particular file:
```
git blame src/science/canopy/cbl_latent_heat.F90
```

It looks like the bug was introduced as part of documentation changes: [07ba229819](https://github.com/CABLE-LSM/CABLE/commit/07ba229819206e8c7fb1b3751e43c64d082851df)

**Comment by JhanSrbinovsky** [comment]
Thanks Sean.

Perhaps that indicates checking necessities following doc changes?


From: Sean Bryan ***@***.***>
Date: Friday, 17 November 2023 at 10:33 am
To: CABLE-LSM/CABLE ***@***.***>
Cc: Srbinovsky, Jhan (Environment, Aspendale) ***@***.***>, Comment ***@***.***>
Subject: Re: [CABLE-LSM/CABLE] Syntax error in serial build (Issue #153)

The git blame command shows which commits had modified a particular file:

git blame src/science/canopy/cbl_latent_heat.F90

It looks like the bug was introduced as part of documentation changes: 07ba229819<https://github.com/CABLE-LSM/CABLE/commit/07ba229819206e8c7fb1b3751e43c64d082851df>
