### ISSUE TITLE
trivial modifications to reconcile ESM1.6:CABLE and CABLE:main

### ISSUE THREAD

**Issue by JhanSrbinovsky** [CABLE-LSM/CABLE#500]
This is the same CABLE sd CABLE:main except: PR to be submitted to main to rm double entry of line:

USE cable_common_module 
in src/science/soilsnow/cbl_surfbv.F90.

remove IF condition around"

IF( .NOT. cable_runtime%um ) THEN
      canopy%cansto =  canopy%oldcansto
ENDIF

in cable_canopy as AM3 comments out the IF condition anyway. Frankly I dont know that we need to as oldcansto is initialised in the "drivers" BUT we need to follow through the intent here as canopy is called multiple times per timestep. @har917 could missing water be the double implicit call and (re-)initialising this?

AND

Not addressed in this issue at all:

PR#497 in CABLE:main to include the developments from AM3 in soilsnow. Mostly to date these are dual densities for liquid/ice water. Single site was unremarkable. Silly me, I did a GSWP2 test which showed a bullseye in Northern Russia. We dont understand why yet, so halting the merger for now. More later.....

AND casa-cnp is not merged. We'll have to think about this. The casa-cnp from AM3 is operational but completely untested. That in CABLE:main is being used offline and in Rachels testing. The AM3 related differences could be trivial anyway, I haven't looked yet.

**Comment by har917** [comment]
@JhanSrbinovsky @ccarouge @martindix a couple of points on this specific issue (but I don't think this has anything to do with our current Siberia quirk in GSWP2 runs).

- I don't understand what that IF/ENDIF is doing in the offline code.  `%cansto` is currently time stepped inside `define_canopy`, `surfbv` happens after that - so this appears to be undoing the time stepping of `%cansto` in the offline code. 
- I am a bit concerned if that line of code is active in AM3 - this could well be the source of the ongoing water imbalance.

Because of the complicated nature of how the UM timesteps somehow or other we are going to have to accommodate some trickery - my vague aspiration has been to get to something where

1. offline time steps as currently - `%cansto` as part of `define_canopy`, nothing else happens afterwards
2. ESM1.5 - `%cansto` is time stepped in `define_canopy` in explicit, reset back to `%oldcansto` in cbm after `define_canopy`, time stepped in define_canopy in implicit
3. CM2/AM3 - `%cansto` is time stepped in `define_canopy` in explicit, reset back to `%oldcansto` in cbm after `define_canopy`; placed into the prognostic bank in implicit, then timestepped in `define_canopy` in implicit (both time through) but reset via the prognostic bank after the first go through.

clear as mud?

In the long run we need to extract the time stepping of `%cansto` out from `define_canopy` as this will help clean up the logic - see #162

**Comment by JhanSrbinovsky** [comment]
@har917 it isnt active in the AM3 model, or the CMIP6 version of ESM1.5. It is blocked by the IF condition. Although it is active in the ESM1.5+CABLE3 version. Probably because offline was doing it. I think your 1,2,3 are in place, I'll have to double check and get back yo you. For 1 however I think my intention was to move it back to offline/cbm where the time-stepping in cbm is the same as in define_canopy anyway and have the same shared canopy for everyone?
