### ISSUE TITLE
Suggest different structure under CABLE/documentation/docs/user_guide

### ISSUE THREAD

**Issue by rkutteh** [CABLE-LSM/CABLE#75]
To me the structure under **CABLE/documentation/docs/user_guide** is not quite right. I think a more reasonable structure would be (ignoring the alphabetical ordering):

- configurations
- inputs
- outputs
- science
- installation
- uber_quick_guide
- tutorials

**configurations** would contain config.md **and/or** user_guide/tutorial/configuration_desc.md
**outputs** would contain user_guide/tutorial/outputs_desc.md
**installation** would contain user_guide/tutorial/compilation.md and user_guide/tutorial/run_cable.md
**uber_quick_guide** would contain user_guide/tutorial/uber_quick_guide.md
**tutorials** would contain actual tutorials (e.g., sample runs with inputs and outputs)

Of course the above folders can also contain additional files in the future but I just moved around what is already there for now.

Another point worth mentioning is I think we should be explicit about which version of CABLE we are describing, as a lot of this info is version specific (maybe include the version number early in the path name). 

Sorry I did not include all of this stuff in a commit/pull_request but I thought a simple Issue is ok at this stage to get feedback.

Ramzi

**Comment by JhanSrbinovsky** [comment]
hmmm - my immediate response was that this would be putting the cart before the horse. An analogy being like choosing the colour of the car before the make and the model. However, this isn't so strange - continuing with the analogy, every time I bought a new car I knew it had to have for e.g. keyless.

I suppose it does make sense to describe "configurations" in a broad sense. However we first have to be clear on what we mean by configurations.
So maybe like 

" CABLE can/is be used in forced single-site investigations (e.g. fluxnet), regional, global. w or out CASA-CNP". 

We probably should steer clear of what is not even available - i.e. BIOS. Claire would know more about worf/lis etc.

"Online in ACCESS, CM2, ESM1.5"
. (Is used in CCAM, TAPM. Has been used in Mk3L - but I think all of these are redundant, at least in terms of availability to general users,

My interpretation of "configurations" though is really what combination of switches are turned on. Which can be the same from single site to ACCESS. i.e. casa=on/off for C,N and P. soil heat flux method = "Humidity Deficit Method", stomatal model ="medlyn", etc. This is the "configurations" meaning that I have grown up with, but happy to discuss further. 

At any rate, the "configurations" listed should definitely be restricted to what is actually provided/supported/made readily accessible.

Jhan

**Comment by JhanSrbinovsky** [comment]
The format on TRAC now reflects (I think) what Claire is saying. From the perspective of a new user (>1/2 of them are students whose supervisor has suggested CABLE). Firstly, how do I get it. Now that I have it, how do I use it.
 Hence the Uber Quick Guide 



1. Download (svn@NCI is problematic for this)
2. module load fortran netcdf and ./build3.sh
3. ./cable

output.nc Is an e.g. of what CABLE does. If this is what you want THEN -this is where it came from,  blardy blah blah
 
- doing this for 10 years (and fielding  the hundreds of new user experiences) it is apparent that people just want to get it and be able to run it, before they look into what they want to change. Hence single site Tumbarumba forcing is shipped with it and corresponding cable.nml etc. It is literally as simple as that. However, I still get annoying comments like Gabs at one of the workshops that CABLE used to be runnable as soon as you got it.  The reality is that it has never been simpler. When I went through the verbatim instructions (see 1,2,3 above) with his grad student who couldn't use it - the response "as always" was "I don't know how I got that wrong". The overarching problem is not the content of the documentation, it is getting people to read it!! I think you will find that he USER guide is complete. It can be improved, certainly updated, but it has not been lacking to exist since circa CMIP5.

**Comment by rkutteh** [comment]
I should clarify at the outset that I was not suggesting any particular order of the categories. That is what I meant by "(ignoring the alphabetical ordering)" but I guess I could have been more clear. I listed the categories in an arbitrary order, as the main feedback I was trying to get was only regarding the extra categories I proposed...

**Comment by JhanSrbinovsky** [comment]
absolutely - we should state explicitly what configs are available/supported.  inputs follows on from this I guess. The inputs side is going to overlap with JAC (on the parameters side at least) - let's try and do this once only :) I cant recall how much we described outputs previously. This would benefit hugely from an "analysis" package. Preferably something we could even link to.

**Comment by ccarouge** [comment]
I agree with putting the outputs descriptions and installation out of the tutorial. I'll change the structure.
